-- use admin role
USE ROLE ACCOUNTADMIN;

-- create 'Transform' role and assign to admin
CREATE ROLE IF NOT EXISTS TRANSFORM;
GRANT ROLE TRANSFORM TO ROLE ACCOUNTADMIN;

-- create a default warehouse
CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH;
GRANT OPERATE ON WAREHOUSE COMPUTE_WH TO ROLE TRANSFORM;

-- create the 'dbt' user and assign it to transform role
CREATE USER IF NOT EXISTS dbt
PASSWORD='YOUR_PASSWORD'
LOGIN_NAME='dbt'
MUST_CHANGE_PASSWORD=FALSE
DEFAULT_WAREHOUSE='COMPUTE_WH'
DEFAULT_ROLE=TRANSFORM
DEFAULT_NAMESPACE='OLIST.RAW'
COMMENT='DBT user used for data transformation';
ALTER USER dbt SET TYPE = LEGACY_SERVICE;
GRANT ROLE TRANSFORM TO USER dbt;

-- create a database and schema for olist project
CREATE DATABASE IF NOT EXISTS OLIST;
CREATE SCHEMA IF NOT EXISTS OLIST.RAW;

-- grant permissions to transform role
GRANT ALL ON WAREHOUSE COMPUTE_WH TO ROLE TRANSFORM;
GRANT ALL ON DATABASE OLIST TO ROLE TRANSFORM;
GRANT ALL ON ALL SCHEMAS IN DATABASE OLIST TO ROLE TRANSFORM;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE OLIST TO ROLE TRANSFORM;
GRANT ALL ON ALL TABLES IN SCHEMA OLIST.RAW TO ROLE TRANSFORM;
GRANT ALL ON FUTURE TABLES IN SCHEMA OLIST.RAW TO ROLE TRANSFORM;
